name: Run FinOps App

on:
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --quiet rich fpdf azure-identity azure-mgmt-resource

      - name: Run FinOps CLI and scripts
        run: |
          set -e
          tmp=$(mktemp)
          python3 finops_cli.py --trend | tee -a "$tmp"
          bash check-budgets.sh | tee -a "$tmp"
          bash detect-waste.sh | tee -a "$tmp"
          bash generate-recommendations.sh | tee -a "$tmp"
          python3 azure_login.py | tee -a "$tmp"
          cat "$tmp" >> "$GITHUB_STEP_SUMMARY"
